engine_type: anthropic
model: claude-sonnet-4-5-20250929
display_name: Claude Sonnet 4.5
temperature: 1.0
thinking:
  type: disabled  # change to "enabled" and set a budget_tokens value to enable thinking
  budget_tokens: 0