price:
  sc_price_reduce_01_percent: '1% Price Reduction'
  sc_price_reduce_05_percent: '5% Price Reduction'
  sc_price_reduce_10_percent: '10% Price Reduction'
instruction:
  sc_instruction_budget: 'Budget'
  sc_instruction_color: 'Color'
  sc_instruction_brand: "Brand"
rating:
  sc_rating_increase_10_bps: 'Rating +0.1'
  sc_rating_random_low_variance: 'Rating (Low Var)'
  sc_rating_random_high_variance: 'Rating (High Var)'
